# Generated by Django 3.1.3 on 2020-11-12 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='id',
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employeeapp.employee'),
        ),
    ]
